#17 Auth login 기능 추가 및 global exception & response entity 리팩토링
CSULBmingle/backend-api pull request #19
Opened 2024-11-06 13:55 UTC by Jiihyun

## Description

> 로그인 기능 구현과
회의 때 정한 global exception 및 response entity 적용

## Changes
<img width="537" alt="image" src="https://github.com/user-attachments/assets/38f87630-5a1a-4cd2-9182-3bb0424026fa">

- WebConfig api path prefix 적용으로 인해 각 컨트롤러에서는 `'/api/v1/'` 이후부터 작성해주면 됩니다. ⭐️
 
<img width="524" alt="image" src="https://github.com/user-attachments/assets/9ebdbeb5-6f45-4f8f-ae3f-b01957e150c5">

- 로그인 후 토큰 보유하고 있는 유저 `@AuthUser` 어노테이션 적용
-> 이 어노테이션을 통해 user를 빼올 수 있습니다.
AuthFilter를 걸어놔서 모든 기능을 다 로그인 후에 할 수 있게 해두었는데,
개발하실 때 `AuthFilter`클래스에서 설정 잠시 풀어주시거나 아니면 위에 사진 처럼 key&value 입력해주시면 될 것 같습니다.

- `ResponseEntity` dto & Global exception 변경한 걸로 AuthController에 적용하였습니다!

## Comment

-  회의하고 이해한 바대로 작성하긴 했는데 잘 했는지 모르겠네요 허허
- 보시고 더 추상화 할 수 있을 것 같거나 불편한 부분있으면 편히 말씀해 주세요
- Global exception은 써본결과,,,괜찮은 것 같으면서도 여전히 클래스 생성할 게 많은 것 같아 조금 귀찮긴 해요😅

2024-11-06 14:57 UTC, devsosin commented
#12 
위 이슈랑 연결해둘게요~

2024-11-07 07:31 UTC, devsosin requested changes
Auth 구현부분은 깔끔한 것 같습니다.
Exception 부분의 추상화를 해제하고 기본 exception을 만든건 제 생각이랑 동일한데,
ExceptionMsg를 추가하면서 errorCode를 enum자료형의 name으로 받고 message만 정의하려고 하신 것 같아요.

exception이 결국 msg까지 생성하게 되면 많아지긴 하는데 최초 1회라... 근데 공통 파일로 관리하면 충돌도 많이 날 것 같아요. 공통 Exception 클래스들은 errorCode만 수정하면 될 것 같아요


ErrorCode를 클래스명으로 가져가면 변환하는 유틸 함수만 만들어놓고 쓸 수 있을 것 같습니다. `String className = this.getClass().getSimpleName();`

```java
public class StringConverter {

    public static String capitalToUpperSnake(String name) {
        StringBuilder result = new StringBuilder();
        
        for (char c : name.toCharArray()) {
            if (Character.isUpperCase(c)) {
                // 대문자 앞에 언더스코어 추가
                if (result.length() > 0) {
                    result.append('_');
                }
            }
            // 문자를 대문자로 변환하여 추가
            result.append(Character.toUpperCase(c));
        }
        
        return result.toString();
    }
}
```

2024-11-07 07:31 UTC, devsosin commented on src/main/java/csulb/mingle/global/error/GlobalExceptionHandler.java
> +     * @param e MissingServletRequestParameterException
MissingServletRequestParameterException은 주로 HTTP 요청의 쿼리 파라미터나 폼 데이터에서 필수 파라미터가 누락되었을 때 발생합니다. 
반면, @NotBlank와 같은 어노테이션은 객체의 필드에 대한 유효성 검사를 수행하며, 이 유효성 검사가 실패하면 MethodArgumentNotValidException이 발생합니다.

이거 아마 오타인것 같은데 MethodArgument~~ 로 바꾸면 될 것 같아요

2024-11-07 07:31 UTC, devsosin commented on src/main/java/csulb/mingle/global/error/exception/BadRequestExceptionMsg.java
> +public enum BadRequestExceptionMsg {
이거 글로벌에 메시지 다 정의해놓고 가져다 사용하면 충돌 많이 날듯합니다

2024-11-07 07:31 UTC, devsosin commented on src/main/java/csulb/mingle/domain/auth/dto/response/RefreshResponse.java
> +public record RefreshResponse(String accessToken) {
이거 관련해서 좀 확인해봤는데 refresh할 때 refreshToken은 프론트에 넘기지 않는게 보안상 더 좋다고 하네요.
refreshToken을 짧게하면 로그인을 자주 해야될 수도 있어서 길게 한 다음 프론트에서 암호화해서 관리하는 방식, 
refreshToken을 다시 발급하는 건 어떻게 할지 고민해봐야겠네요

2024-11-07 07:31 UTC, devsosin commented on src/main/java/csulb/mingle/global/filter/AuthFilter.java
> +        if (shouldSkipFilter(request)) {
method명은 skipFilter 정도로만 둬도 되지 않을까요?

2024-11-07 07:31 UTC, devsosin commented
이거 제가 exception 부분만 브랜치 따로 파서 작업해볼게요

2024-11-07 08:59 UTC, devsosin approved these changes

2024-11-11 18:23 UTC, Jiihyun commented on src/main/java/csulb/mingle/domain/auth/dto/response/RefreshResponse.java
> +public record RefreshResponse(String accessToken) {
엇 현재 refresh할 때는 프론트에 accessToken만 넘기고 있고, 
처음에 로그인 할 때만 accessToken이랑 refreshToken 같이 넘겨줘요. 
현재 access 유효기간 1시간, refresh 1년으로 해두었습니다!

2024-11-11 18:23 UTC, Jiihyun commented on src/main/java/csulb/mingle/global/error/exception/BadRequestExceptionMsg.java
> +public enum BadRequestExceptionMsg {
그쵸,,저도 작성하면서 어랏..? 머지할 떄 충돌이 날 수 있겠는데 생각했지만,,일단 작성해보았습니다

2024-11-11 18:38 UTC, Jiihyun commented on src/main/java/csulb/mingle/global/error/exception/BadRequestExceptionMsg.java
> +public enum BadRequestExceptionMsg {
그쵸,,? 저도 이부분을 공용으로 사용하다보면 충돌 많이 일어날 것 같다는 생각을 했는데,,,일단 작성해보았습니다!

2024-11-11 18:38 UTC, Jiihyun commented on src/main/java/csulb/mingle/domain/auth/controller/AuthController.java
> +    public ResponseEntity<SuccessResponse> requestVerification(@Valid @RequestBody SendEmailRequest request) {
오홍 구체타입보다는 추상타입으로 두는 게 더 좋을 것 같네요. 
반영하겠습니다👍🏻

2024-11-11 18:38 UTC, Jiihyun commented on src/main/java/csulb/mingle/domain/auth/service/AuthService.java
> +            throw new NotFoundException(USER_NOT_FOUND);
그렇게 구체적으로 이름을 해두면 예외사항들 모두 커스텀 예외를 만들어야 할까봐, 일단은 HTTP_STATUS_NAME으로 다 만들어 두었습니다..!

2024-11-11 18:38 UTC, Jiihyun commented on src/main/java/csulb/mingle/global/error/GlobalExceptionHandler.java
> +     * @param e MissingServletRequestParameterException
오 좋은 캐치 감사합니다!
주석을 수정 안하였네요.. 반영했습니다👍🏻

2024-11-11 19:26 UTC, merged